version: '3.8'
services: 
  contact-keeper-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: contact-keeper-backend
    ports:
      - '5000:5000'
    env_file:
      - ./config/config.env