version: '3.8'
services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: contact-keeper-backend
    ports:
      - '5000:5000'
    env_file:
      - ./backend/config/config.env
    volumes: 
      - ./backend:/app/backend
      - /app/backend/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: contact-keeper-frontend
    ports:
      - '3000:3000'
    depends_on: 
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    stdin_open: true
    tty: true

    
